### ISSUE TITLE
Planeación de Recursos

### ISSUE THREAD

**Issue by Anna-Aparicio** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-equipo-cb-24h#1]
[Planificacion del proyecto.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-equipo-cb-24h/files/7557243/Planificacion.del.proyecto.pdf)

**Comment by Eva155** [comment]
CALIFICACIÓN: 20 Puntos
CALIFICÓ: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Bien hecho y revisado
